suggestions = {
    r'uo$': 'uyor',
    r'ıo$': 'ıyor',
    r'io$': 'iyor',
    r'üo$': 'üyor',
    r'iyo$': 'iyor',
    r'ıyo$': 'ıyor',
    r'uyo$': 'uyor',
    r'üyo$': 'üyor',
    r'yolar': 'yorlar',
    r'yodu$': 'yordu',
    r'yomuş': 'yormuş',

    r'io(ru)?m$': 'iyorum',
    r'ıo(ru)?m$': 'ıyorum',
    r'iyom$': 'iyorum',
    r'ıyom$': 'ıyorum',
    r'uyom$': 'uyorum',
    r'üyom$': 'üyorum',

    r'iyon$': 'iyorsun',
    r'uyon$': 'uyorsun',
    r'ıyon$': 'ıyorsun',
    r'üyon$': 'üyorsun',
    r'uos': 'uyors',
    r'ıos': 'ıyors',
    r'ios': 'iyors',
    r'üos': 'üyors',
    r'iyos': 'iyors',
    r'ıyos': 'ıyors',
    r'uyos': 'uyors',
    r'üyos': 'üyors',

    r'iyonuz$': 'iyorsunuz',
    r'uyonuz$': 'uyorsunuz',
    r'ıyonuz$': 'ıyorsunuz',
    r'üyonuz$': 'üyorsunuz',


    r'iyoz$': 'iyoruz',
    r'ıyoz$': 'ıyoruz',
    r'uyoz$': 'uyoruz',
    r'üyoz$': 'üyoruz',

    r'ioz$': 'iyoruz',
    r'ıoz$': 'ıyoruz',
    r'iyoz$': 'iyoruz',
    r'ıyoz$': 'ıyoruz',
    r'uyoz$': 'uyoruz',
    r'üyoz$': 'üyoruz',

    r'[uı]cak': 'acak',
    r'icek': 'ecek',
    r'lcek': 'lecek',
    r'lcak': 'lacak',
    r'micek': 'meyecek',
    r'mıcek': 'mayacak',
    r'macak': 'mayacak',
    r'mecek': 'meyecek',
    r'iycek': 'eyecek',
    r'ıycak': 'ayacak',

    r'[uı]cağ': 'acağ',
    r'iceğ': 'eceğ',
    r'miceğ': 'meyeceğ',
    r'mıceğ': 'mayacağ',
    r'macağ': 'mayacağ',
    r'meceğ': 'meyeceğ',
    r'iyceğ': 'eyeceğ',
    r'ıycağ': 'ayacağ',

    r'[ıau]caz$': 'acağız',
    r'[ie]cez$': 'eceğiz',
    r'micez$': 'meyeceğiz',
    r'mıcaz$': 'mayacağız',
    r'iycez$': 'eyeceğiz',
    r'ıycaz$': 'ayacağız',

    r'[auı]cam$': 'acağım',
    r'[ie]cem$': 'eceğim',
    r'mıcam$': 'mayacağım',
    r'micem$': 'meyeceğim',
    r'iycem': 'eyecem',
    r'ıycam': 'ayacam',

    r'eğe$': 'eye',
    r'ağa$': 'aya',

    r'lari': 'ları',

    r'e?cen$': 'eceksin',
    r'[auı]?can$': 'acaksın',

    r'olca(k|ğ)': 'olacak',
    r'^isıt': 'ısıt',
    r'^isit': 'ısıt',
    r'^isın': 'ısın',
    r'^isin': 'ısın',

    r'̇z': 'z',
    r'̇r': 'r',
    r'̇̇̇ṁ': 'm',
    r'̇̇̇ẏ': 'y',
    r'̇n': 'n',
}
