suggestions = {
    r'^olca(k|ğ)': 'olacak',
    r'^[iı]s[ıi]t': 'ısıt',
    r'^[iı]s[iı]n': 'ısın',
    r'^[iı]s[ıi]r': 'ısır',
    r'^et[cç]e': 'edece',
    r'^yapilaşma': 'yapılaşma',
    r'^ismar': 'ısmar',
    r'^gımıl': 'kımıl',
    r'^isbat': 'ispat',
    r'^miril': 'mıril',
    r'^taptuk': 'taptık',
    r'^yabanci': 'yabancı',
    r'^heycan': 'heyecan',
    r'^haykiriri': 'haykırırı',
    r'^haykiri': 'haykırı',
    r'^haykir': 'haykır',
    r's[iı]n[iı]fland[iı]r[iı]lmas[iı]': 'sınıflandırılması',
    r'^sinif': 'sınıf',
    r'^farkli': 'farklı',
    r'^tika': 'tıka',
    r'^kacak': 'kucak',
    r'^zayifl': 'zayıf',
    r'^danişma': 'danış',
    r'^aydin': 'aydın',

    r'uo$': 'uyor',
    r'ıo$': 'ıyor',
    r'io$': 'iyor',
    r'üo$': 'üyor',
    r'iyo$': 'iyor',
    r'ıyo$': 'ıyor',
    r'uyo$': 'uyor',
    r'üyo$': 'üyor',
    r'yolar': 'yorlar',
    r'yodu': 'yordu',
    r'yomuş': 'yormuş',

    r'io(ru)?m$': 'iyorum',
    r'ıo(ru)?m$': 'ıyorum',
    r'iyom$': 'iyorum',
    r'ıyom$': 'ıyorum',
    r'uyom$': 'uyorum',
    r'üyom$': 'üyorum',

    r'iyon$': 'iyorsun',
    r'uyon$': 'uyorsun',
    r'ıyon$': 'ıyorsun',
    r'üyon$': 'üyorsun',
    r'uos': 'uyors',
    r'ıos': 'ıyors',
    r'ios': 'iyors',
    r'üos': 'üyors',
    r'iyos': 'iyors',
    r'ıyos': 'ıyors',
    r'uyos': 'uyors',
    r'üyos': 'üyors',

    r'iyonuz$': 'iyorsunuz',
    r'uyonuz$': 'uyorsunuz',
    r'ıyonuz$': 'ıyorsunuz',
    r'üyonuz$': 'üyorsunuz',


    r'iyoz$': 'iyoruz',
    r'ıyoz$': 'ıyoruz',
    r'uyoz$': 'uyoruz',
    r'üyoz$': 'üyoruz',

    r'ioz$': 'iyoruz',
    r'ıoz$': 'ıyoruz',
    r'iyoz$': 'iyoruz',
    r'ıyoz$': 'ıyoruz',
    r'uyoz$': 'uyoruz',
    r'üyoz$': 'üyoruz',

    r'[uı]cak': 'acak',
    r'icek': 'ecek',
    r'lcek': 'lecek',
    r'lcak': 'lacak',
    r'micek': 'meyecek',
    r'mıcek': 'mayacak',
    r'macak': 'mayacak',
    r'mecek': 'meyecek',
    r'iycek': 'eyecek',
    r'ıycak': 'ayacak',

    r'[uı]cağ': 'acağ',
    r'iceğ': 'eceğ',
    r'miceğ': 'meyeceğ',
    r'mıceğ': 'mayacağ',
    r'macağ': 'mayacağ',
    r'meceğ': 'meyeceğ',
    r'iyceğ': 'eyeceğ',
    r'ıycağ': 'ayacağ',
    r'mıcanı':  'mayacağını',

    r'[ıau]caz$': 'acağız',
    r'[ie]cez$': 'eceğiz',
    r'micez$': 'meyeceğiz',
    r'mıcaz$': 'mayacağız',
    r'iycez$': 'eyeceğiz',
    r'ıycaz$': 'ayacağız',

    r'[auı]cam$': 'acağım',
    r'[ie]cem$': 'eceğim',
    r'mıcam$': 'mayacağım',
    r'micem$': 'meyeceğim',
    r'iycem': 'eyecem',
    r'ıycam': 'ayacam',

    r'e?cen$': 'eceksin',
    r'[auı]?can$': 'acaksın',

    r'eğe$': 'eye',
    r'ağa$': 'aya',

    r'lari$': 'ları',

    r'̇z': 'z',
    r'̇r': 'r',
    r'̇̇̇ṁ': 'm',
    r'̇̇̇ẏ': 'y',
    r'̇n': 'n',
}
